let thing = [
  {
    "#": "1",
    date: "2013-04-02",
    name: "Peaches",
    difficulty: "5.6",
    diff_sort: "6",
    pitches: "1",
    grade: "1",
    area: "NV> RR> Willow Spring> Children's Crag",
    rock: "Sandstone",
    partner: "Ward Opfer",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/peaches/105732950",
    notes:
      "First Trad lead, easy climbing. I traversed to the right late. Need 70m or doubles to rap?",
  },
  {
    "#": "2",
    date: "2013-04-04",
    name: "Physical Graffiti",
    difficulty: "5.6",
    diff_sort: "6",
    pitches: "2",
    grade: "2",
    area: "NV> RR> Calico Basin> Riding Hood Wall",
    rock: "Sandstone",
    partner: "Ron Safarik, Kyle Bauer",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/physical-graffiti/105732266",
    notes:
      "Second ever trad lead, first multipitch. Turned into a minor epic: couldn't find rap anchors, first time dealing with a group of 3 on a multipitch, ended up traversing and rapping down Big Bad Wolf, which is only the most popular route in Nevada. Yeah...",
  },
  {
    "#": "3",
    date: "2013-06-21",
    name: "Treebeard",
    difficulty: "5.8-",
    diff_sort: "8",
    pitches: "1",
    grade: "1",
    area: "AR> HCR> Confederate Cracks",
    rock: "Sandstone",
    partner: "Kyle Bauer",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/treebeard/106243491",
    notes: "Trad lead, weird in places, but good",
  },
  {
    "#": "4",
    date: "2013-07-14",
    name: "Boston",
    difficulty: "5.7",
    diff_sort: "7",
    pitches: "2",
    grade: "2",
    area: "TX> Erock> Main Dome> Cheap Wine Wall",
    rock: "Granite",
    partner: "Gavin Echterling",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/boston/105860322",
    notes:
      "OS lead first pitch, v.sketchy flakes that take cams fine. Don't fall. Gavin lead DomeDriver p2.",
  },
  {
    "#": "5",
    date: "2014-01-19",
    name: "Sweat",
    difficulty: "5.7",
    diff_sort: "7",
    pitches: "1",
    grade: "1",
    area: "TX> Erock> Main Dome> News Wall",
    rock: "Granite",
    partner: "",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/sweat/105862559",
    notes: "OS trad lead, good practice. (have lead this multiple times now)",
  },
  {
    "#": "6",
    date: "2014-04-09",
    name: "Lion Tamer",
    difficulty: "5.9-",
    diff_sort: "9",
    pitches: "1",
    grade: "1",
    area: "AR> HCR> North Forty",
    rock: "Sandstone",
    partner: "",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/lion-tamer/105976426",
    notes:
      "Climbed 3 times. TR, TR mock trad lead, then trad lead. Some nut and cam placements and of course chicken heads to sling. Good practice on easy stuff.",
  },
  {
    "#": "7",
    date: "2014-04-09",
    name: "Missing Rack",
    difficulty: "5.7",
    diff_sort: "7",
    pitches: "1",
    grade: "1",
    area: "AR> HCR> North Forty",
    rock: "Sandstone",
    partner: "Kyle Bauer",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/missing-rack/109665140",
    notes:
      "trad lead, 2 pieces next to each other, but they wouldn't have saved me from decking. Lay back to hand jam to throw shoulder and feet into crack and squeeze chimney to chimney at top, sport anchors. Very short 1 move wonder. Named missing rack as you really don't need to bring any gear.",
  },
  {
    "#": "8",
    date: "2014-04-10",
    name: "The Catholic Boat",
    difficulty: "5.9",
    diff_sort: "9",
    pitches: "1",
    grade: "1",
    area: "AR> HCR> Crackhouse Alley",
    rock: "Sandstone",
    partner: "Kyle Bauer",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/the-catholic-boat/109526182",
    notes:
      "trad lead, got pretty scared at my last piece of protection, a old single stem style c4 that i couldn't get a good safe placement with while pumped out of my gourd and feet killing me, fighting rope drag, may have hit ledge below me on rope stretch if it didn't hold, etc... Hung like 2-3x at this cam then managed to get a good placement and get to the anchors",
  },
  {
    "#": "9",
    date: "2014-04-11",
    name: "Gaius",
    difficulty: "5.7+",
    diff_sort: "7",
    pitches: "1",
    grade: "1",
    area: "AR> HCR> Roman Wall",
    rock: "Sandstone",
    partner: "Kyle Bauer",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/gaius/109665376",
    notes: "trad lead, kyle followed IIRC",
  },
  {
    "#": "10",
    date: "2014-06-01",
    name: "Tradical Buzzards (FA?)",
    difficulty: "5.7",
    diff_sort: "7",
    pitches: "1",
    grade: "1",
    area: "TX> Reimer's Ranch North Shore> Buzzards Roof",
    rock: "Limestone",
    partner: "Gavin Echterling",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/tradical-buzzards/109060264",
    notes: "trad lead first ascent (?), gavin followed",
  },
  {
    "#": "11",
    date: "2014-07-20",
    name: "Sweat",
    difficulty: "5.7",
    diff_sort: "7",
    pitches: "1",
    grade: "1",
    area: "TX> Erock> Main Dome> News Wall",
    rock: "Granite",
    partner: "Maria Bisaga",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/sweat/105862559",
    notes:
      "trad lead, maria's first time following and cleaning trad placements",
  },
  {
    "#": "12",
    date: "2014-07-27",
    name: "Jack knife",
    difficulty: "5.5",
    diff_sort: "5",
    pitches: "1",
    grade: "1",
    area: "TX> Erock> Echo Canyon> Throne Rock Area",
    rock: "Granite",
    partner: "Maria Bisaga",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/jack-knife/105872732",
    notes:
      "trad lead, was trying to get to cave crack but couldn't find it, rope got stuck 3x!!! w/maria",
  },
  {
    "#": "13",
    date: "2014-11-26",
    name: "Crooked Crack",
    difficulty: "5.6",
    diff_sort: "6",
    pitches: "1",
    grade: "1",
    area: "NV> RR> Willow Spring> Ragged Edges Area",
    rock: "Sandstone",
    partner: "Maria Bisaga",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/crooked-crack/106133493",
    notes:
      "W/Maria. Belayed from a large feature I slung with cord. Couldn't find rap anchors, traversed to rap as Ok Ok Ok.",
  },
  {
    "#": "14",
    date: "2014-11-26",
    name: "Peaches",
    difficulty: "5.6",
    diff_sort: "6",
    pitches: "1",
    grade: "1",
    area: "NV> RR> Willow Spring> Children's Crag",
    rock: "Sandstone",
    partner: "Maria Bisaga",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/peaches/105732950",
    notes: "Lead again, maria followed",
  },
  {
    "#": "15",
    date: "2014-11-27",
    name: "Birdland",
    difficulty: "5.7+",
    diff_sort: "7",
    pitches: "6",
    grade: "3",
    area: "NV> RR> Pine Creek Canyon> Brass Wall",
    rock: "Sandstone",
    partner: "Maria Bisaga",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/birdland/105733115",
    notes:
      "Excellent! Lead 2,3, and 5th pitches w/Maria. Did not bother with 6th pitch per friend's advice. Helped out a couple trying to bail off an 11R to the right while we were decending. Spectrum? Spectrum roof? Our rap station was higher than they were. I rapped down a bit so I was about level with them, they tossed me an end of their rope, then I ascended back up to our bolted anchor, passed it through and tossed it back to them so they would be set up for rappel off of it. Maria and I then rapped down. Guy and Girl chose to simulrappel AND traverse quite a bit while going down. Had warned them of the swing potential before we set this up but they said that they had done worse and I incorrectly trusted in their ablility. It was enough of a traverse that they couldn't stay completely weighted on the rope as you need to be for a simulrap, someone probably stood up or used a handhold for a second causing the other to suddenly drop a bit and lose their footing. Girl took a traversing against the wall swing/fall with barrel rolls, was shaken but \"OK\" . Did the rest of the raps to the bottom of the climb fine (also as simulraps), then she started freaking out a bit. Loopy. Had to leave our packs at the base, jog/walk/run to parking lot to get cell service, call in ambulence and helicopter, wait for police/ambulance to chat with them about the situation then hike back to get our packs. Girl and Guy walked out helicopter ground crew guys found them and chatted with them. Didn't stick around to find out if the girl decided to take the heli to the hospital or not. Apparently its a free service in Red Rock Canyon NCA? Ate jack in the box at like 1am for thanksgiving dinner... Lots of bad things happened. There were better ways we could have helped. We trusted in their ability and experience without knowing them personally and this was a bad idea. This was the reason I decided to take a WFR class... For one, if they had just built a gear anchor and bailed, that would have been fast and best for everyone, I should have encouraged this choice more. Else, to reduce the swing angle, I could have re-lead the pitch we had just rapped down from with one end of their rope, then set it up for rapp so their traverse would be a very mellow angle, though this would have taken longer and it was already very dark. Its also possible that the guy could have trad-lead traversed the face between us to get to our anchor, girl following/cleaning. It looked pretty do-able, but hard to know how good the face holds were. I'm thankful for \"light cannon\" headlamps that run off 18650 lithium ion batteries.",
  },
  {
    "#": "16",
    date: "2014-11-28",
    name: "Physical Graffiti",
    difficulty: "5.6",
    diff_sort: "6",
    pitches: "2",
    grade: "2",
    area: "NV> RR> Calico Basin> Riding Hood Wall",
    rock: "Sandstone",
    partner: "Maria Bisaga",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/physical-graffiti/105732266",
    notes:
      "Maria trad led first pitch, I trad led 2nd. Can't remember exact date... Most likely the 28th. We took the walk off or the rap + walk off, can't remember, either way we were not going down big bad wolf like last time I was here.",
  },
  {
    "#": "17",
    date: "2015-05-31",
    name: "Chimney Crack",
    difficulty: "5.6",
    diff_sort: "6",
    pitches: "1",
    grade: "1",
    area: "TX> Erock> Little Dome> Kingdom of Zilch> Sci-Fi wall",
    rock: "Granite",
    partner: "Maria Bisaga",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/chimney-crack/106961988",
    notes:
      "Trad lead, forgot how unforgiving erock granite cracks are. Had to hang. Do again.",
  },
  {
    "#": "18",
    date: "2015-11-26",
    name: "Tunnel Vision",
    difficulty: "5.7+",
    diff_sort: "7",
    pitches: "6",
    grade: "3",
    area: "NV> RR> White Rock Spring> Angel Food Wall",
    rock: "Sandstone",
    partner: "Maria Bisaga",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/tunnel-vision/105732509",
    notes:
      "Damn. This route was scary. Type 2 fun in a lot of places for sure. Or well... Lots of type 1 fun, but scared about the possibility of falling with pro far apart... It's kinda a blur now. I led first pitch, it has a weird kinda bouldering start and traverse. I placed a cam, traversed, placed another and then traversed back to clean the first to reduce rope drag... ??? ... Maria led 2nd, it was a ton of kinda intimidating moves somewhat chimney but using face moves, back stepping, etc. Proud of her. She was done after her pitch. I lead the rest of the pitches, but had her lead accross the horizontal traverse at the end since I already had her on belay. Accidently left a pink tricam and sling in the dark, another group w/Du climbed the route the next day and returned it at the rental house. The squeeze chimney parts on this were cool but freaky. I was only expecting the tunnel pitch to be the chimney part, instead this route was chimneys everywhere. As well did the tunnel on far left as a squeeze to feet/back stem chimney instead of whatever is normal. Route was a pain with my homemade white D40 alpine-style bag in tow, though I guess it gave it a good thrashing/durability test. If I ever do this route again, must make sure to only have a simple water bladder and the follower carries it or otherwise go fast and light.",
  },
  {
    "#": "19",
    date: "2015-11-29",
    name: "Olive Oil",
    difficulty: "5.7",
    diff_sort: "7",
    pitches: "5",
    grade: "3",
    area: "NV> RR> Juniper Canyon> Rose Tower",
    rock: "Sandstone",
    partner: "Maria Bisaga",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/olive-oil/105732494",
    notes:
      "Mellow. Mostly face climbing on great crimps and jugs. Maria led 1st pitch to wrong anchor, then dropped a cam (#3). So she lowered me on a munter, I retrieved it, climbed back up, got the rack down-lead-climbed to the proper belay spot placing ~3 pieces so she would have a safer traverse follow. Cluster then started with multiple groups coming up and getting to the proper belay just as we were getting there. I led next linking the 2nd and 3rd pitches with a 70m. Was a really damn cool pitch. Chill easy climbing with a great crack for protection. I would like to try it another time jamming the crack more than using the face, but I felt rushed from the multiple groups. Made the belay to the right of the normal belay spot as otherwise it would become very crowded. Then maria led the next pitch and traversed to the top of the column thing. Was hard for her to build an anchor there, not the best options. Then I lead the 5th pitch up the corner to the top. Parts of the corner were a little interesting, some slight intimidation with run outs, but everything was there. Protection opportunities were not the best in some places. Additionally there was some chimney, like full on knees on one side feet on the other chimney. Maybe 8-12' hard to remember exactly. Little intimidating with not amazing placements below, but short and felt fairly secure. Used 3 aliens for the last belay then went over easy stuff to the right and followed cairns for descent. Nitecore headlamp batt was dead, like no voltage dead so had to share Maria's. Will keep a small backup headlamp or spare batt in my chalkbag for future MP. ",
  },
  {
    "#": "20",
    date: "2016-01-31",
    name: "Sweat",
    difficulty: "5.7",
    diff_sort: "7",
    pitches: "1",
    grade: "1",
    area: "TX> Erock> Main Dome> News Wall",
    rock: "Granite",
    partner: "Paul Frost",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/sweat/105862559",
    notes:
      "trad lead yet again, then top belayed Paul Frost up so he could clean my placements, thhen I lowered him on a munter (just to quickly get him out of the way), and he tied another rope on to his harness and top rope - mock trad lead it to see if he felt comfortable on lead. He did, so we both rapped down and then he trad lead it and I cleaned and critiqued his placements. We ended up climbing it 3 times each.",
  },
  {
    "#": "21",
    date: "2016-01-31",
    name: "Owl Crack",
    difficulty: "5.8+",
    diff_sort: "8",
    pitches: "1",
    grade: "1",
    area: "TX> Erock> Echo Canyon> Triple Cracks",
    rock: "Granite",
    partner: "Paul Frost",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/owl-crack/105902520",
    notes:
      "trad lead finally! I have been apprehensive about this crack for some time now. On several trips out here I have thought about leading it and decided not to. Finally did it today. I have been spending too much time at Austin Bouldering Project, a lot of my endurance is gone, I pumped out and had to rest multiple times, but didn't hang. The first ~2 protection placements on this thing are very easy to accidently knock around and hard to avoid doing so. High up I followed the main flake and went a little too high, had to down climb/clean about 15ft then traverse over to the anchor, which is quite far to the left and shared with all 4 of the main routes at the triple cracks sanctuary. (Owl, middle, beckys, grass). Some other routes are pretty close to here too, but I don't know that much about them. Paul followed and cleaned, then I lowered him on a munter just to get him down fast and declutter. Then I set up for rappelling, over-under coiled my rope starting with both ends so that when tossing it would be much less likely to get caught on any flakes or make knots. Tossed, rapped, and pulled without issues. Maybe next time I'm in the area I'll do it again... and MAYBE do middle crack too. Beckys is intimidating to try to protect and climb if you do it in the pure offwidth start style.",
  },
  {
    "#": "22",
    date: "2016-03-25",
    name: "Hudson Crack",
    difficulty: "5.8",
    diff_sort: "8",
    pitches: "1",
    grade: "1",
    area: "AR> Cowell Area> Hudson Mtn",
    rock: "Sandstone",
    partner: "Gavin Echterling?",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/hudson-crack/110167961",
    notes:
      "trad lead. Was a pretty cool crack to lead. Definitely had to jam a lot. Very glad I did it. Gavin got some incredible pictures. Date approximate.",
  },
  {
    "#": "23",
    date: "2016-03-25",
    name: "Earl's Revenge",
    difficulty: "5.7",
    diff_sort: "7",
    pitches: "1",
    grade: "1",
    area: "AR> HCR> North Forty",
    rock: "Sandstone",
    partner: "",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/earls-revenge/110428873",
    notes:
      "trad lead. Nice to tick another trad lead off, and glad I did so before I got too sick and had to bail on the rest of the trip. The single bolt at the crux is nice as there isn't really any protection opportunity at that point and holds get sparse. Date approximate.",
  },
  {
    "#": "24",
    date: "2016-05-21",
    name: "Little Feat",
    difficulty: "5.9",
    diff_sort: "9",
    pitches: "1",
    grade: "1",
    area: "TX> Erock> Buzzard's Roost> E.Face",
    rock: "Granite",
    partner: "David Gawalt",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/little-feat/105984717",
    notes:
      "trad lead. Hung once, will need to do again. Extend top placement(s) before anchors to reduce rope drag for follower and leave last piece with sling as a directional if top-roping.",
  },
  {
    "#": "25",
    date: "2016-06-20",
    name: "Top Choice",
    difficulty: "5.10-",
    diff_sort: "10",
    pitches: "1",
    grade: "1",
    area: "TX> Erock> Little Dome> Carnivore Boulders",
    rock: "Granite",
    partner: "David Gawalt",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/top-choice/106744907",
    notes:
      "trad lead. Hung at most every placement, then even more at the top crux. Tape glove strips rolled up. I need to get the sequence for the top nailed down, then lead it clean.",
  },
  {
    "#": "26",
    date: "2016-06-29",
    name: "Pumper No. 9",
    difficulty: "5.8",
    diff_sort: "8",
    pitches: "1",
    grade: "1",
    area: "TX> Erock> Little Dome> Lizardhead Boulders",
    rock: "Granite",
    partner: "David Gawalt",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/pumper-number-9/106943824",
    notes:
      "trad lead / onsight. Started by stepping off onto it from the boulder giving a est. grade of 5.8. Supposidly standing start is 5.9+ (I couldn't get it... sandbagged? Will have to try again sometime). Sit start at the back of the cave is supposed to be 5.12a-ish. Yowza. Used two #3 and 1 #2 C4 up top for the anchor. Used a 0.75 as a directional at the start, then #1-3-ish on route.",
  },
  {
    "#": "27",
    date: "2016-07-01",
    name: "Sweat",
    difficulty: "5.7",
    diff_sort: "7",
    pitches: "1",
    grade: "1",
    area: "TX> Erock> Main Dome> News Wall",
    rock: "Granite",
    partner: "David Baeza",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/sweat/105862559",
    notes:
      "trad lead. placed excess protection for the benefit of David Baeza to clean it while teaching him basic trad climbing cam and nut placements",
  },
  {
    "#": "28",
    date: "2016-07-01",
    name: "Beginner's Bitch",
    difficulty: "5.7+",
    diff_sort: "7",
    pitches: "1",
    grade: "1",
    area: "TX> Erock> Echo Canyon> Motorboat Rock",
    rock: "Granite",
    partner: "David Baeza",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/beginners-bitch/105878327",
    notes:
      "trad lead. Did not feel like very much of the rock was trustably solid for gear placements, pretty much only solid once your near the top.",
  },
  {
    "#": "29",
    date: "2016-07-01",
    name: "Navy Route",
    difficulty: "5.8",
    diff_sort: "8",
    pitches: "1",
    grade: "1",
    area: "TX> Erock> Echo Canyon> Motorboat Rock",
    rock: "Granite",
    partner: "David Baeza",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/navy-route/106719676",
    notes:
      "trad lead. Too chossy at the top to risk topping out, so set up a top anchor first, then lead up to it to clip it. Slab beginning is certainly the crux. Hung once before commiting to a move. Middle portion of crack is great. Top portion gets chossy again.",
  },
  {
    "#": "30",
    date: "2016-07-01",
    name: "Jack Knife",
    difficulty: "5.5",
    diff_sort: "5",
    pitches: "1",
    grade: "1",
    area: "TX> Erock> Echo Canyon> Throne Rock Area",
    rock: "Granite",
    partner: "David Baeza",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/jack-knife/105872732",
    notes:
      "trad lead. On way to cave crack with David B. Have lead it previously and followed david g. 2 other times.",
  },
  {
    "#": "31",
    date: "2016-07-01",
    name: "Cave Crack",
    difficulty: "5.6",
    diff_sort: "6",
    pitches: "1",
    grade: "1",
    area: "TX> Erock> Echo Canyon> Orange Peel Area",
    rock: "Granite",
    partner: "David Baeza",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/cave-crack/105872738",
    notes:
      "trad lead. Good stuff. Should have saved 1 of the 2 #4s for higher up, ended up running it out quite a bit above a #3.5, but on the very easy slab up in the sun. W/David B.",
  },
  {
    "#": "32",
    date: "2016-07-03",
    name: "Bush Crack",
    difficulty: "5.9",
    diff_sort: "9",
    pitches: "1",
    grade: "1",
    area: "TX> Erock> Buzzard's Roost> SW Face",
    rock: "Granite",
    partner: "David Gawalt",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/bush-crack/105902563",
    notes:
      "trad lead. Clean lead, no hangs! Had TR'd on previous ocassions. Almost fell near the top. I mostly used the face for feet, will need to lead this again sometime using the crack more for feet like I had previously done when TR'ing it. Built anchor to TR with David G. and he spent a very long time trying to recover some gear a previous party dropped, with a clothes hanger, to no avail. We need to build an extra long nut tool we can hammer on, coat hanger was too flimsy for this.",
  },
  {
    "#": "33",
    date: "2016-07-16",
    name: "Cave Crack",
    difficulty: "5.6",
    diff_sort: "6",
    pitches: "1",
    grade: "1",
    area: "TX> Erock> Echo Canyon> Orange Peel Area",
    rock: "Granite",
    partner: "Sean Murphy, David Gawalt, Rong Ma",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/cave-crack/105872738",
    notes:
      "trad lead. Fantastic climb as always. Belayed Shawn M? up, who was tailing the middle of a 70m, with which I belayed up David G., and then Rong... I could have let one of the two climb up about 15-20 ft and then have the other one start up and have them just keep their pace about the same so I could belay them both up simultaneously. I'll need to practice belaying two people at once at another time.",
  },
  {
    "#": "34",
    date: "2016-07-20",
    name: "Jack Knife",
    difficulty: "5.5",
    diff_sort: "5",
    pitches: "1",
    grade: "1",
    area: "TX> Erock> Echo Canyon> Throne Rock Area",
    rock: "Granite",
    partner: "",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/jack-knife/105872732",
    notes: "trad lead. Date approximate. Put it up for others to TR.",
  },
  {
    "#": "35",
    date: "2016-09-03",
    name: "Bass Down Low",
    difficulty: "5.7",
    diff_sort: "7",
    pitches: "1",
    grade: "1",
    area: "AR> HCR> New Roman Wall",
    rock: "Sandstone",
    partner: "David Gawalt",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/bass-down-low/111109853",
    notes:
      "trad lead. Dirty and cobweb filled chimney. Suspicions that it was the reason for insane amounts of chigger bites later for both of us. No one else on the trip had chigger trouble.",
  },
  {
    "#": "36",
    date: "2016-09-03",
    name: "Ghosts of Mississippi",
    difficulty: "5.9+",
    diff_sort: "9",
    pitches: "1",
    grade: "1",
    area: "AR> HCR> New Roman Wall",
    rock: "Sandstone",
    partner: "David Gawalt",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/ghosts-of-mississippi/111109861",
    notes: "trad lead. One or two interesting moves.",
  },
  {
    "#": "37",
    date: "2016-09-03",
    name: "First Time Up",
    difficulty: "5.8+",
    diff_sort: "8",
    pitches: "1",
    grade: "1",
    area: "AR> HCR> The Far East",
    rock: "Sandstone",
    partner: "David Gawalt",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/first-time-up/105988241",
    notes:
      "trad lead. David tried leading it first. He had to hang/lower to get more gear, then couldn't make it throught the commiting layback crux. Lowered him. Pulled the rope. I re-lead it removing/replacing his cams in a few spots. Had to hang at the crux to lower to get more gear as he did, then had to hang at the crux several times. Finally got up. The way the layback flake angles to the right makes it a good idea to extend pieces, else they will want to rotate as you climb above them, had this happen to both of us... thus the moving down a few moves, re-adjusting the cam in question and hanging on it. This is a great looking route.",
  },
  {
    "#": "38",
    date: "2016-09-04",
    name: "WMA Crack",
    difficulty: "5.9+",
    diff_sort: "9",
    pitches: "1",
    grade: "1",
    area: "AR> HCR> Confederate Cracks",
    rock: "Sandstone",
    partner: "David Gawalt",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/wma-crack/105986617",
    notes:
      "trad lead. Fantastic route! Brought and placed a new #5 and #6 because I could. Most of the route was pretty straight forward with a few slightly spicy sections. Top flared thin hands section was crux for me. Almost had to hang.",
  },
  {
    "#": "39",
    date: "2016-09-04",
    name: "Hackberry Crack",
    difficulty: "5.9",
    diff_sort: "9",
    pitches: "1",
    grade: "1",
    area: "AR> HCR> Walls of Moria",
    rock: "Sandstone",
    partner: "David Gawalt",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/hackberry-crack/106063523",
    notes:
      "trad lead. Fun stuff! Hung 1-2x. Had trouble with fist jams in one part. Will need to re-lead it another time!",
  },
  {
    "#": "40",
    date: "2016-09-04",
    name: "Breach",
    difficulty: "5.9PG13",
    diff_sort: "9",
    pitches: "1",
    grade: "1",
    area: "AR> HCR> Titanic Boulder",
    rock: "Sandstone",
    partner: "Ron Safarik belayed",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/breach/106124133",
    notes:
      "trad lead. Fun route! Would have more stars and traffic if someone would clean out the rotten rock about 2/3's up. There were 2 newer anchors that are more convienient and more safe than needing to climb out the roof on questionable rock as stated in guidebooks. Ron belayed me. I cleaned placements on rap... Next time I'm here I'd like to have a go at Starboard List, the 5.11a thin hands crack on the back of this boulder.",
  },
  {
    "#": "41",
    date: "2016-10-01",
    name: "Sweat",
    difficulty: "5.7",
    diff_sort: "7",
    pitches: "1",
    grade: "1",
    area: "TX> Erock> Main Dome> News Wall",
    rock: "Granite",
    partner: "Brian Luna, Christopher Smith, Ilsa, Alvaro",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/sweat/105862559",
    notes:
      "trad lead. Placed excess protection for Ilsa to learn more about gear placements.",
  },
  {
    "#": "42",
    date: "2016-10-01",
    name: "Cave Crack",
    difficulty: "5.6",
    diff_sort: "6",
    pitches: "1",
    grade: "1",
    area: "TX> Erock> Echo Canyon> Orange Peel Area",
    rock: "Granite",
    partner: "Brian Luna, Christopher Smith, Ilsa, Alvaro",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/cave-crack/105872738",
    notes:
      "trad lead. Bypassed jackknife and hard hands and took a quick little path one of the RockAbout guides showed me. Top belayed everyone else up one at a time.",
  },
  {
    "#": "43",
    date: "2016-10-01",
    name: "Dan Jam",
    difficulty: "5.8",
    diff_sort: "8",
    pitches: "1",
    grade: "1",
    area: "TX> Erock> Buzzards Roost> SW Face",
    rock: "Granite",
    partner: "Brian Luna, Christopher Smith, Ilsa, Alvaro",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/dan-jam/106896464",
    notes:
      "trad lead. Previously called this unknown 5.8 OW to squeeze chimney to the left of Bush Crack. Finally lead this. Did it clean. Placed 3 pieces. C4 #5, #6, then a single bigbro #4 before starting the squeeze chimney. Set up an anchor with #1, #2, #2 for everyone else to TR off of, then reconfigure for Bush crack later.",
  },
  {
    "#": "44",
    date: "2016-10-01",
    name: "Bush Crack",
    difficulty: "5.9",
    diff_sort: "9",
    pitches: "1",
    grade: "1",
    area: "TX> Erock> Buzzards Roost> Sw Face",
    rock: "Granite",
    partner: "Brian Luna, Christopher Smith, Ilsa, Alvaro",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/bush-crack/105902563",
    notes:
      "trad lead... sorta. Brian attempted to lead this and gave up with gear to about half-way. I re-moved/re-placed a few then placed a few more as I lead past what he had placed to finish it up. Hung 2x this time.",
  },
  {
    "#": "45",
    date: "2016-10-21",
    name: "Little Feat",
    difficulty: "5.9",
    diff_sort: "9",
    pitches: "1",
    grade: "1",
    area: "TX> Erock> Buzzard's Roost> E.Face",
    rock: "Granite",
    partner: "John Deas, Michael Klein",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/little-feat/105984717",
    notes:
      "trad lead. Clean and quick. Then a TR lap forcing all thumbs up jams and a TR lap forcing all thumbs down jams. #0.75 for directional, then #1, #2, #3, #3.5, #4... IIRC.",
  },
  {
    "#": "46",
    date: "2016-11-04",
    name: "Jack Knife",
    difficulty: "5.5",
    diff_sort: "5",
    pitches: "1",
    grade: "1",
    area: "TX> Erock> Echo Canyon> Throne Rock Area",
    rock: "Granite",
    partner: "John Deas",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/jack-knife/105872732",
    notes:
      "trad lead. SPI assessment. We didn't want to get on anything too hard due to recent heavy rain.",
  },
  {
    "#": "47",
    date: "2016-11-18",
    name: "Jack Knife",
    difficulty: "5.5",
    diff_sort: "5",
    pitches: "1",
    grade: "1",
    area: "TX> Erock> Echo Canyon> Throne Rock Area",
    rock: "Granite",
    partner: "clients",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/jack-knife/105872732",
    notes:
      "trad lead. Top belayed up client 1, lowered them off backside. Top belayed up client 2, lowered them off backside. Rapped down to them.",
  },
  {
    "#": "48",
    date: "2016-11-18",
    name: "Cave Crack",
    difficulty: "5.6",
    diff_sort: "6",
    pitches: "1",
    grade: "1",
    area: "TX> Erock> Echo Canyon> Orange Peel Area",
    rock: "Granite",
    partner: "clients",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/cave-crack/105872738",
    notes:
      "trad lead. Top belayed up client 1. Top belayed up client 2. Walked off together.",
  },
  {
    "#": "49",
    date: "2016-11-19",
    name: "Dan Jam",
    difficulty: "5.8",
    diff_sort: "8",
    pitches: "1",
    grade: "1",
    area: "TX> Erock> Buzzards Roost> SW Face",
    rock: "Granite",
    partner: "Christopher Smith, Kelly Lawrence, ???",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/dan-jam/106896464",
    notes: "trad lead. Used same gear as previously. Felt just as solid on it.",
  },
  {
    "#": "50",
    date: "2016-11-19",
    name: "High Octane",
    difficulty: "5.11a",
    diff_sort: "11",
    pitches: "1",
    grade: "1",
    area: "TX> Erock> Little Dome> Carnivore Boulders",
    rock: "Granite",
    partner: "Christopher Smith, Kelly Lawrence, ???",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/high-octane/106744928",
    notes:
      "trad lead. Hung once when I couldn't get my foot up to the good pod. First trad 11. Will need to do another time clean.",
  },
  {
    "#": "51",
    date: "2016-11-24",
    name: "Can Opener",
    difficulty: "5.7+",
    diff_sort: "7",
    pitches: "1",
    grade: "1",
    area: "TX> Erock> Echo Canyon> Motorboat Rock",
    rock: "Granite",
    partner: "Brian Luna",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/can-opener/107443736",
    notes:
      "trad lead. Hung once about mid-way up. Awkward crack for me and rope was getting in my way.",
  },
  {
    "#": "52",
    date: "2016-11-24",
    name: "Ben's Dilemma",
    difficulty: "5.9-",
    diff_sort: "9",
    pitches: "1",
    grade: "1",
    area: "TX> Erock> Echo Canyon> Motorboat Rock",
    rock: "Granite",
    partner: "Brian Luna",
    on_mp: "yes",
    link: "http://www.mountainproject.com/v/bens-dilemma/106588220",
    notes:
      "trad lead. Took my time and messed around. Placed BigBro#3, BD #5, #6, #4, #3, #3 IIRC",
  },
  {
    "#": "53",
    date: "2016-12-17",
    name: "Top Choice",
    difficulty: "5.10-",
    diff_sort: "10",
    pitches: "1",
    grade: "1",
    area: "TX> Erock> Little Dome> Carnivore Boulders",
    rock: "Granite",
    partner: "Kelly Lawrence, Edward Shierk",
    on_mp: "yes",
    link: "https://www.mountainproject.com/v/top-choice/106744907",
    notes:
      "trad lead. 1 hang at crux. Wayyy better than last time I tried to lead it. Placed 9 pieces total.",
  },
  {
    "#": "54",
    date: "2016-12-18",
    name: "Dan Jam",
    difficulty: "5.8",
    diff_sort: "8",
    pitches: "1",
    grade: "1",
    area: "TX> Erock> Buzzards Roost> SW Face",
    rock: "Granite",
    partner: "Kelly Lawrence, Rob",
    on_mp: "yes",
    link: "https://www.mountainproject.com/v/dan-jam/106896464",
    notes:
      "trad lead. Clean lead on this for the 3rd time. Temp was in the 20s.",
  },
  {
    "#": "55",
    date: "2016-12-27",
    name: "No Sweat",
    difficulty: "5.5",
    diff_sort: "5",
    pitches: "1",
    grade: "1",
    area: "TX> Erock> Main Dome> News Wall",
    rock: "Granite",
    partner: "clients",
    on_mp: "yes",
    link: "https://www.mountainproject.com/v/no-sweat/105862567",
    notes: "trad lead. For clients, to get Sweat 5.7 up.",
  },
  {
    "#": "56",
    date: "2017-01-22",
    name: "Scrambled Egg Sandwich",
    difficulty: "5.10+",
    diff_sort: "10",
    pitches: "1",
    grade: "1",
    area: "TX> Erock> Little Dome> Kingdom of Zilch> The Kingdom",
    rock: "Granite",
    partner: "Kelly Lawrence, Christopher Smith",
    on_mp: "yes",
    link: "https://www.mountainproject.com/v/scrambled-egg-sandwich/105984988",
    notes:
      "trad lead. 1 hang. This crack is awesome! Why oh why didn't I get on this thing before now?! Should get it clean next time!",
  },
  {
    "#": "57",
    date: "2017-02-11",
    name: "Top Choice",
    difficulty: "5.10-",
    diff_sort: "10",
    pitches: "1",
    grade: "1",
    area: "TX> Erock> Little Dome> Carnivore Boulders",
    rock: "Granite",
    partner: "Kelly Lawrence, Christopher Smith, Spencer",
    on_mp: "yes",
    link: "https://www.mountainproject.com/v/top-choice/106744907",
    notes:
      "trad lead(s). 1 hang at crux when I botched the sequence, pulled the top pro, lowered, and re-lead it with the lower easy pro already placed, but I still moved it around a bit and placed top pro during crux getting it clean.",
  },
  {
    "#": "58",
    date: "2017-02-12",
    name: "Thin Crack",
    difficulty: "5.5",
    diff_sort: "5",
    pitches: "1",
    grade: "1",
    area: "TX> BCGB> Gus Fruh",
    rock: "Limestone",
    partner: "Kelly Lawrence",
    on_mp: "yes",
    link: "https://www.mountainproject.com/v/thin-crack/106085170",
    notes: "trad/mixed lead.",
  },
  {
    "#": "59",
    date: "2017-02-12",
    name: "Flash Crack",
    difficulty: "5.7",
    diff_sort: "7",
    pitches: "1",
    grade: "1",
    area: "TX> BCGB> Gus Fruh",
    rock: "Limestone",
    partner: "Kelly Lawrence",
    on_mp: "yes",
    link: "https://www.mountainproject.com/v/flash-crack/112134969",
    notes: "trad/mixed lead.",
  },
  {
    "#": "60",
    date: "2017-03-10",
    name: "Treebeard",
    difficulty: "5.8-",
    diff_sort: "8",
    pitches: "1",
    grade: "1",
    area: "AR> HCR> Walls of Moria",
    rock: "Sandstone",
    partner: "Kelly Lawrence",
    on_mp: "yes",
    link: "https://www.mountainproject.com/v/treebeard/106243491",
    notes:
      "trad lead. Finished Kelly's partial lead. Frigid cold. Sleep deprived.",
  },
  {
    "#": "61",
    date: "2017-03-10",
    name: "Starboard List",
    difficulty: "5.11a",
    diff_sort: "11",
    pitches: "1",
    grade: "1",
    area: "AR> HCR> Titanic Boulder",
    rock: "Sandstone",
    partner: "Kelly Lawrence",
    on_mp: "yes",
    link: "https://www.mountainproject.com/v/starboard-list/105977216",
    notes:
      "trad lead, hanging, aiding. Did the first 2-3 moves well and placed gear fine, then messed up the sequence and had a hard time reaching the solid jams. Had to hang a lot and ended up aiding many moves. Frigid cold and sleep deprived. Will have to try again another time.",
  },
  {
    "#": "62",
    date: "2017-03-12",
    name: "Fat Crack",
    difficulty: "5.6",
    diff_sort: "6",
    pitches: "1",
    grade: "1",
    area: "AR> Sam's Throne> The Throne> White Trash Wall",
    rock: "Sandstone",
    partner: "Christopher Smith, Kelly Lawrence, Gavin Ecterling",
    on_mp: "yes",
    link: "https://www.mountainproject.com/v/fat-crack/105906503",
    notes:
      "trad lead, hang twice? Very cold and wet. I couldn't feel or effectively use my fingers. I remembered that I hate climbing in the cold for a reason.",
  },
  {
    "#": "63",
    date: "2017-03-12",
    name: "Boston Rag",
    difficulty: "5.7",
    diff_sort: "7",
    pitches: "1",
    grade: "1",
    area: "AR> Sam's Throne> The Throne> White Trash Wall",
    rock: "Sandstone",
    partner: "Christopher Smith, Kelly Lawrence, Gavin Ecterling",
    on_mp: "yes",
    link: "https://www.mountainproject.com/v/boston-rag/105906498",
    notes: "trad lead. Clean. Very cold, but this climb was mostly dry.",
  },
  {
    "#": "64",
    date: "2017-03-12",
    name: "Lazy Arch",
    difficulty: "5.7",
    diff_sort: "7",
    pitches: "1",
    grade: "1",
    area: "AR> Sam's Throne> The Throne> White Trash Wall",
    rock: "Sandstone",
    partner: "Christopher Smith, Kelly Lawrence, Gavin Ecterling",
    on_mp: "yes",
    link: "https://www.mountainproject.com/v/lazy-arch/108895610",
    notes:
      "trad lead. Clean. Did this to set up a TR on Tandem Slide aka Last Waltz 5.9+",
  },
  {
    "#": "65",
    date: "2017-04-19",
    name: "Gilgamek Vagina",
    difficulty: "5.9",
    diff_sort: "9",
    pitches: "1",
    grade: "1",
    area: "AR> HCR> Walls of Moria",
    rock: "Sandstone",
    partner: "Gavin Ecterling",
    on_mp: "yes",
    link: "https://www.mountainproject.com/v/gilgamek-vagina/106243478",
    notes: "trad lead. Clean OS. Wish top part went on for days.",
  },
  {
    "#": "66",
    date: "2017-04-19",
    name: "Deft Jam",
    difficulty: "5.9+",
    diff_sort: "9",
    pitches: "1",
    grade: "1",
    area: "AR> HCR> Confederate Cracks",
    rock: "Sandstone",
    partner: "Gavin Ecterling",
    on_mp: "yes",
    link: "https://www.mountainproject.com/v/deft-jam/106060483",
    notes: "trad lead. Clean. Wet last 10-ish feet",
  },
  {
    "#": "67",
    date: "2017-04-20",
    name: "Poison Ivy",
    difficulty: "5.7+",
    diff_sort: "7",
    pitches: "1",
    grade: "1",
    area: "AR> Sam's Throne> The Throne> Poison Ivy Wall",
    rock: "Sandstone",
    partner: "Gavin Ecterling, Kyle Bauer",
    on_mp: "yes",
    link: "https://www.mountainproject.com/v/poison-ivy/105901659",
    notes:
      "trad lead. Clean. Looks awesome. Doesn't feel particularly awesome to climb, IMO, just eye candy.",
  },
  {
    "#": "68",
    date: "2017-04-20",
    name: "Mike's Crack",
    difficulty: "5.10b",
    diff_sort: "10",
    pitches: "1",
    grade: "1",
    area: "AR> Sam's Throne> The Throne> Blind Man's Bluff",
    rock: "Sandstone",
    partner: "Gavin Ecterling, Kyle Bauer",
    on_mp: "yes",
    link: "https://www.mountainproject.com/v/mikes-crack/105968661",
    notes:
      "trad lead. Clean. No particularly hard moves, but slightly overhanging the whole way. I made too much pump for me by messing up the cam size I grabbed off my harness twice in the beginning... once it was time to clip the anchors I had to shake out and alternate a bunch just to be able to clip.",
  },
  {
    "#": "69",
    date: "2017-04-20",
    name: "Too Thick To Navigate",
    difficulty: "5.8+",
    diff_sort: "8",
    pitches: "1",
    grade: "1",
    area: "AR> Sam's Throne> The Throne> Blind Man's Bluff",
    rock: "Sandstone",
    partner: "Gavin Ecterling, Kyle Bauer",
    on_mp: "yes",
    link: "https://www.mountainproject.com/v/too-thick-to-navigate/105906319",
    notes: "trad lead. Clean. Bottom is kinda cool. Top is kinda meh.",
  },
  {
    "#": "70",
    date: "2017-05-06",
    name: "Top Choice",
    difficulty: "5.10-",
    diff_sort: "10",
    pitches: "1",
    grade: "1",
    area: "TX> Erock> Little Dome> Carnivore Boulders",
    rock: "Granite",
    partner: "Christopher Smith, Kelly Lawrence",
    on_mp: "yes",
    link: "https://www.mountainproject.com/v/top-choice/106744907",
    notes: "trad lead. Clean. Was very solid on this lead this time.",
  },
  {
    "#": "71",
    date: "2017-05-26",
    name: "Atomic Knee Drop",
    difficulty: "5.6",
    diff_sort: "6",
    pitches: "1",
    grade: "1",
    area: "OK> Wichita Wildlife Refuge> Mount Scott> Upper Mount Scott",
    rock: "Granite",
    partner: "Christopher Smith, Kelly Lawrence",
    on_mp: "yes",
    link: "https://www.mountainproject.com/v/atomic-knee-drop/105885259",
    notes:
      "trad lead. Clean. Very easy. Some finger crack stuff up higher which would be really cool if this route was closer to vertical.",
  },
  {
    "#": "72",
    date: "2017-05-26",
    name: "Unnamed off-width crack",
    difficulty: "5.8",
    diff_sort: "8",
    pitches: "1",
    grade: "1",
    area: "OK> Wichita Wildlife Refuge> Mount Scott> Upper Mount Scott",
    rock: "Granite",
    partner: "Christopher Smith, Kelly Lawrence",
    on_mp: "yes",
    link: "https://www.mountainproject.com/v/unnamed-off-width-crack/105971198",
    notes:
      "trad lead. Clean. Used a few small cams in side cracks as well as a BD #5, #6, and Valley Giant #12 as a pusher piece to the top.",
  },
  {
    "#": "73",
    date: "2017-05-27",
    name: "The Dihedral",
    difficulty: "5.6",
    diff_sort: "6",
    pitches: "1",
    grade: "1",
    area: "OK> Wichita Wildlife Refuge> The Narrows> Zoo Wall",
    rock: "Granite",
    partner: "Christopher Smith, Kelly Lawrence, Will Fenwick",
    on_mp: "yes",
    link: "https://www.mountainproject.com/v/the-dihedral/105861314",
    notes:
      "trad lead. Clean. Very polished and slick. Felt 5.8-ish to me from this alone.",
  },
  {
    "#": "74",
    date: "2017-05-27",
    name: "Crazy Alice",
    difficulty: "5.8",
    diff_sort: "8",
    pitches: "1",
    grade: "1",
    area: "OK> Wichita Wildlife Refuge> The Narrows> Zoo Wall",
    rock: "Granite",
    partner: "Christopher Smith, Kelly Lawrence, Will Fenwick",
    on_mp: "yes",
    link: "https://www.mountainproject.com/v/crazy-alice/105860080",
    notes:
      "trad lead. Clean. Finished Kelly's partial lead. They say this is the best 5.8 in the park, I wasn't impressed.",
  },
  {
    "#": "75",
    date: "2017-05-28",
    name: "High Anxiety",
    difficulty: "5.7",
    diff_sort: "7",
    pitches: "1",
    grade: "1",
    area: "OK> Wichita Wildlife Refuge> Mount Scott> Lower Mount Scott",
    rock: "Granite",
    partner: "Christopher Smith, Kelly Lawrence, Will Fenwick",
    on_mp: "yes",
    link: "https://www.mountainproject.com/v/high-anxiety/105904882",
    notes: "trad lead. Clean. Fun route! Gobbles up gear.",
  },
  {
    "#": "76",
    date: "2017-05-28",
    name: "Mr. Clean",
    difficulty: "5.8",
    diff_sort: "8",
    pitches: "1",
    grade: "1",
    area: "OK> Wichita Wildlife Refuge> Mount Scott> Lower Mount Scott",
    rock: "Granite",
    partner: "Christopher Smith, Kelly Lawrence, Will Fenwick",
    on_mp: "yes",
    link: "https://www.mountainproject.com/v/mr-clean/105914923",
    notes: "trad lead. Clean. Fun route!",
  },
  {
    "#": "77",
    date: "2017-06-25",
    name: "Scrambled Egg Sandwich",
    difficulty: "5.10+",
    diff_sort: "10",
    pitches: "1",
    grade: "1",
    area: "TX> Erock> Little Dome> Kingdom of Zilch> The Kingdom",
    rock: "Granite",
    partner: "Kelly Lawrence, Lee Payne",
    on_mp: "yes",
    link: "https://www.mountainproject.com/v/scrambled-egg-sandwich/105984988",
    notes:
      "trad lead. Clean. Climbs out over a pit. Placed the first cam from the ground/boulder, climbed up placing two more, had some miscommunication with my belayer which took too long to sort out and pumped me out too much, I hung, downclimbed and cleaned all gear except for the placed from the ground/boulder piece, took a few minutes to rest and got on it again, getting it clean, but barely as I still had not completely recovered.",
  },
  {
    "#": "78",
    date: "2017-07-01",
    name: "Left Side",
    difficulty: "5.5",
    diff_sort: "0",
    pitches: "1",
    grade: "1",
    area: "CO> Boulder> Boulder Canyon> Happy Hour Crag",
    rock: "Granite",
    partner: "Kelly Lawrence, Kathleen, Boyan",
    on_mp: "yes",
    link: "https://www.mountainproject.com/v/left-side/105973231",
    notes:
      "trad lead. Clean. Something easy to get used to the rock and give example placements for Kathleen and Boyan.",
  },
  {
    "#": "79",
    date: "2017-07-01",
    name: "Are We Not Men?",
    difficulty: "5.7PG13",
    diff_sort: "0",
    pitches: "1",
    grade: "1",
    area: "CO> Boulder> Boulder Canyon> Happy Hour Crag",
    rock: "Granite",
    partner: "Kelly Lawrence, Kathleen, Boyan",
    on_mp: "yes",
    link: "https://www.mountainproject.com/v/are-we-not-men/105748373",
    notes: "trad lead. Clean.",
  },
  {
    "#": "80",
    date: "2017-07-01",
    name: "Malign",
    difficulty: "5.7",
    diff_sort: "0",
    pitches: "1",
    grade: "1",
    area: "CO> Boulder> Boulder Canyon> Happy Hour Crag",
    rock: "Granite",
    partner: "Kelly Lawrence, Kathleen, Boyan",
    on_mp: "yes",
    link: "https://www.mountainproject.com/v/malign/105756556",
    notes: "trad lead. Clean. Kinda weird traversing route.",
  },
  {
    "#": "81",
    date: "2017-07-01",
    name: "Dementia",
    difficulty: "5.10a",
    diff_sort: "0",
    pitches: "1",
    grade: "1",
    area: "CO> Boulder> Boulder Canyon> Happy Hour Crag",
    rock: "Granite",
    partner: "Kelly Lawrence, Kathleen, Boyan",
    on_mp: "yes",
    link: "https://www.mountainproject.com/v/dementia/105748412",
    notes:
      "trad lead. 1 hang at crux. Some interesting movement getting up to the dihedral too.",
  },
  {
    "#": "82",
    date: "2017-07-02",
    name: "Finger Crack",
    difficulty: "5.9",
    diff_sort: "0",
    pitches: "1",
    grade: "1",
    area: "CO> Boulder> Boulder Canyon> Nip and Tuck",
    rock: "Granite",
    partner: "Kelly Lawrence, Kathleen, Boyan",
    on_mp: "yes",
    link: "https://www.mountainproject.com/v/finger-crack/105748352",
    notes:
      "trad lead. Clean. Fun route! Plenty of hand and feet options in and outside of the crack.",
  },
  {
    "#": "83",
    date: "2017-07-04",
    name: "The Bastille Crack",
    difficulty: "5.7",
    diff_sort: "0",
    pitches: "5",
    grade: "2",
    area: "CO> Boulder> Eldorado Canyon SP> The Bastille > N Face",
    rock: "Conglomerate Sandstone",
    partner: "Kelly Lawrence",
    on_mp: "yes",
    link: "https://www.mountainproject.com/v/the-bastille-crack/105748490",
    notes:
      "trad lead. Clean. I lead 1,3,4th pitches w/Kelly. She was having a bad day. Very nauseated but at the end she still wanted to lead the final chimney (she normally hates chimneys) so some mixed type 1 and 2 fun for her on this climb.",
  },
  {
    "#": "84",
    date: "2017-07-04",
    name: "Blind Faith",
    difficulty: "5.10a",
    diff_sort: "0",
    pitches: "2",
    grade: "1",
    area: "CO> Boulder> Eldorado Canyon SP> The Bastille > W Face",
    rock: "Conglomerate Sandstone",
    partner: "Kelly Lawrence",
    on_mp: "yes",
    link: "https://www.mountainproject.com/v/blind-faith/105748639",
    notes:
      "trad lead. 1 hang at crux. I chose the hand crack crux over the finger crack crux, but from above the finger crack crux looked more fun. The chimney or trough a bit below was awkward with so much gear on my harness. Kelly wasn't feeling great. We were both tired and dehydrated. Decided to bail instead of doing the next pitch.",
  },
  {
    "#": "85",
    date: "2017-07-05",
    name: "Huston Crack",
    difficulty: "5.8-",
    diff_sort: "0",
    pitches: "1",
    grade: "1",
    area: "CO> Boulder> Boulder Canyon> Cob Rock",
    rock: "Granite",
    partner: "Kelly Lawrence",
    on_mp: "yes",
    link: "https://www.mountainproject.com/v/huston-crack/105756784",
    notes: "trad lead. 1-2 hangs. Afterwards TR'd with a few different styles.",
  },
  {
    "#": "86",
    date: "2017-07-06",
    name: "North Face Center",
    difficulty: "5.7+",
    diff_sort: "0",
    pitches: "2",
    grade: "1",
    area: "CO> Boulder> Boulder Canyon> Cob Rock",
    rock: "Granite",
    partner: "Kelly Lawrence",
    on_mp: "yes",
    link: "https://www.mountainproject.com/v/north-face-center/105748093",
    notes: "trad lead. Kelly lead first pitch. I led a long second pitch.",
  },
  {
    "#": "87",
    date: "2017-07-08",
    name: "White Whale",
    difficulty: "5.7",
    diff_sort: "0",
    pitches: "4",
    grade: "2",
    area: "CO> Estes Park Valley> Lumpy Ridge> Left Book",
    rock: "Granite",
    partner: "Kelly Lawrence",
    on_mp: "yes",
    link: "https://www.mountainproject.com/v/white-whale/105750013",
    notes:
      "trad lead. Kelly lead 1st. I bailed on 2nd due to imminent rain/lightning. Left 2 DMM nuts, alpine runner, 2 wiregates.",
  },
];
